### ISSUE TITLE
macos(intel) 下报错“[-] 查找安装路径时出错：No module named 'winreg'”，手动设置 wechatEXEpath 后还是报错,wx3.8.8

### ISSUE THREAD

**Issue by gemmi** [JaveleyQAQ/WeChatOpenDevTools-Python#102]
macos 下执行`python main.py -c`报错，找不到 winreg 模块，查看代码似乎是需要找到微信可执行程序路径然后拉起来，见这个代码，于是手动设置了wechatEXEpath变量，结果执行时还是报错。
<img width="965" alt="image" src="https://github.com/user-attachments/assets/2683f5af-a17f-4fbd-9861-bb6214a1744e">

```bash
aaa WeChatOpenDevTools-Python$ python main.py -c
 _       ___  __    ____           ______            __    
| |     / / |/ /   / __ \___ _   _/_  __/___  ____  / /____
| | /| / /|   /   / / / / _ \ | / // / / __ \/ __ \/ / ___/
| |/ |/ //   |   / /_/ /  __/ |/ // / / /_/ / /_/ / (__  ) 
|__/|__//_/|_|  /_____/\___/|___//_/  \____/\____/_/____/  
                                                           

	

    
        公众号: 一位不愿透露姓名的热心网友
        Github：https://github.com/JaveleyQAQ
    

path:  /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx
Traceback (most recent call last):
  File "/Users/aaa/Projects/github/WeChatOpenDevTools-Python/main.py", line 41, in <module>
    main()
  File "/Users/aaa/Projects/github/WeChatOpenDevTools-Python/main.py", line 31, in main
    commons.load_wechatEXE_configs()
  File "/Users/aaa/Projects/github/WeChatOpenDevTools-Python/utils/commons.py", line 89, in load_wechatEXE_configs
    self.inject_wechatDLL(wechatEXEpath, wechatEXE_hookcode)
  File "/Users/aaa/Projects/github/WeChatOpenDevTools-Python/utils/commons.py", line 40, in inject_wechatDLL
    session = frida.attach(pid)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frida/__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.TimedOutError: unexpectedly timed out while initializing suspended process
```

**Comment by JaveleyQAQ** [comment]
mac无-c选项
