### ISSUE TITLE
大佬 救命！！！ python  main.py -c 无法启动微信

### ISSUE THREAD

**Issue by 2934714194** [JaveleyQAQ/WeChatOpenDevTools-Python#117]
![image](https://github.com/user-attachments/assets/9cdc251f-cedc-4050-b812-4f6d0402a447)

[+] 查找到微信的安装路径是：C:\Program Files\Tencent\WeChat\WeChat.exe
[+] 正在尝试重启微信...
Traceback (most recent call last):
  File "C:\Users\29347\Desktop\WeChatOpenDevTools-Python-main\main.py", line 41, in <module>
    main()
  File "C:\Users\29347\Desktop\WeChatOpenDevTools-Python-main\main.py", line 31, in main
    commons.load_wechatEXE_configs()
  File "C:\Users\29347\Desktop\WeChatOpenDevTools-Python-main\utils\commons.py", line 82, in load_wechatEXE_configs
    self.inject_wechatDLL(wechatEXEpath, wechatEXE_hookcode)
  File "C:\Users\29347\Desktop\WeChatOpenDevTools-Python-main\utils\commons.py", line 37, in inject_wechatDLL
    pid = self.device.spawn(path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29347\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\29347\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\frida\core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unable to spawn executable at 'C:\Program Files\Tencent\WeChat\WeChat.exe': 0x00000032

**Comment by JaveleyQAQ** [comment]
把进程都关了再试试 不会就重启电脑直接运行-c
