### ISSUE TITLE
# 是否支持Mac，看readme以为支持mac，实际运行了一下报错

### ISSUE THREAD

**Issue by Aralhi** [JaveleyQAQ/WeChatOpenDevTools-Python#48]
## 问题描述

python main.py -x
Traceback (most recent call last):
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/main.py", line 3, in <module>
    from utils.commons import Commons
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/utils/commons.py", line 4, in <module>
    from utils.wechatutils import WechatUtils
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/utils/wechatutils.py", line 1, in <module>
    import os,re,winreg
ModuleNotFoundError: No module named 'winreg'

## 环境信息
- **操作系统及版本**：macOS Sonoma 14.4.1
- **编程语言和版本**：python 3.10
- **相关库或框架及版本**：github源码未做任何修改
- **GitHub 仓库名称和问题相关的代码分支**：JaveleyQAQ/WeChatOpenDevTools-Python main分支

## 复现步骤
1. 步骤一：git clone git@github.com:JaveleyQAQ/WeChatOpenDevTools-Python.git
2. 步骤二：cd WeChatOpenDevTools-Python
3. 步骤三：pip3  install -r requirements.txt
4. 步骤四：python main.py -x

Traceback (most recent call last):
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/main.py", line 3, in <module>
    from utils.commons import Commons
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/utils/commons.py", line 4, in <module>
    from utils.wechatutils import WechatUtils
  File "/Users/katakuri/Documents/ai/WeChatOpenDevTools-Python/utils/wechatutils.py", line 1, in <module>
    import os,re,winreg
ModuleNotFoundError: No module named 'winreg'

## 预期结果
- 期望正常运行

## 实际结果
- ModuleNotFoundError: No module named 'winreg'

## 附加文件

查了下winreg是window下的包，但貌似运行又强依赖的了，所以macos下无法运行

**Comment by JaveleyQAQ** [comment]
#45

**Comment by Aralhi** [comment]
非常感谢这么高效率的评价issue，👍🏻

**Comment by sdogsq** [comment]
楼主解决了吗，是不是最终mac无解，没有winreg
