### ISSUE TITLE
执行python  main.py -c报错，开启不了内嵌浏览器的devtools

### ISSUE THREAD

**Issue by wangchangjiu** [JaveleyQAQ/WeChatOpenDevTools-Python#91]
[-] 查找安装路径时出错：name 'winreg' is not defined
Traceback (most recent call last):
  File "E:\Github\WeChatOpenDevTools-Python\main.py", line 41, in <module>
    main()
  File "E:\Github\WeChatOpenDevTools-Python\main.py", line 31, in main
    commons.load_wechatEXE_configs()
  File "E:\Github\WeChatOpenDevTools-Python\utils\commons.py", line 65, in load_wechatEXE_configs
    self.inject_wechatDLL(wechatEXEpath, wehcatEXE_hookcode)
  File "E:\Github\WeChatOpenDevTools-Python\utils\commons.py", line 32, in inject_wechatDLL
    pid = self.device.spawn(path)
  File "E:\Github\WeChatOpenDevTools-Python\venv\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "E:\Github\WeChatOpenDevTools-Python\venv\lib\site-packages\frida\core.py", line 959, in spawn
    if isinstance(argv[0], bytes):
TypeError: 'NoneType' object is not subscriptable

**Comment by blueyer** [comment]
![image](https://github.com/user-attachments/assets/e81214ba-ba60-4fe7-8a91-9dcbc35c5496)

**Comment by JaveleyQAQ** [comment]
解决了，把winreg作用域搞错了
