### ISSUE TITLE
# 在mac M2机型上出现报错

### ISSUE THREAD

**Issue by open-nan** [JaveleyQAQ/WeChatOpenDevTools-Python#95]
机型：Mac m2
操作系统：macOS Sonoma V14.1.2
cpu架构: ARM64
python版本:  3.11.7

报错信息： 
```sh
(base) WeChatOpenDevTools-Python % python main.py -x

__      ____  __  ___          _____         _    
\ \    / /\ \/ / |   \ _____ _|_   _|__  ___| |___
 \ \/\/ /  >  <  | |) / -_) V / | |/ _ \/ _ \ (_-<
  \_/\_/  /_/\_\ |___/\___|\_/  |_|\___/\___/_/__/
                                                  

	

    
        公众号: 一位不愿透露姓名的热心网友
        Github：https://github.com/JaveleyQAQ
    

Traceback (most recent call last):
  File "/Users/nan/code/ijm_project/enc-issue/WeChatOpenDevTools-Python/main.py", line 41, in <module>
    main()
  File "/Users/nan/code/ijm_project/enc-issue/WeChatOpenDevTools-Python/main.py", line 29, in main
    commons.load_wechatEx_configs()
  File "/Users/nan/code/ijm_project/enc-issue/WeChatOpenDevTools-Python/utils/commons.py", line 45, in load_wechatEx_configs
    pid, version = self.wechatutils_instance.get_wechat_pid_and_version_mac()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nan/code/ijm_project/enc-issue/WeChatOpenDevTools-Python/utils/wechatutils.py", line 81, in get_wechat_pid_and_version_mac
    return int(pid),version
           ^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Cenergy** [comment]
你要打开微信再运行程序

**Comment by open-nan** [comment]
@Cenergy 我同时开启了微信和微信开发者工具，然后运行程序依然会报这个错误，它貌似找不到pid
<img width="959" alt="image" src="https://github.com/user-attachments/assets/48069603-f0ea-4226-b196-7334282ecba1">

**Comment by JaveleyQAQ** [comment]
没有支持m系

**Comment by open-nan** [comment]
我好像明白了，微信在我的电脑上的进程名是wechat 而不是 WeChatAppEx
<img width="758" alt="image" src="https://github.com/user-attachments/assets/95664175-1291-4ac1-ba20-aaa816a43098">

**Comment by open-nan** [comment]
@JaveleyQAQ 好吧

**Comment by Cenergy** [comment]
[WeChatOpenDevTools-Python-arm](https://github.com/f4l1k/WeChatOpenDevTools-Python-arm) 这个支持

**Comment by JaveleyQAQ** [comment]
> @JaveleyQAQ 好吧

 http://sndav.org/archives/open-wechat-miniprogram-devtools-m1  这里有分析

**Comment by JaveleyQAQ** [comment]
> > @JaveleyQAQ 好吧
> 
> http://sndav.org/archives/open-wechat-miniprogram-devtools-m1 这里有分析

https://blog.naive.codes/archives/open-wechat-miniprogram-devtools-m1
